// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcialplataformas;

namespace Parcialplataformas.Migrations
{
    [DbContext(typeof(parcialdbcontext))]
    [Migration("20201010050759_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Parcialplataformas.Detalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnName("Fecha")
                        .HasColumnType("DateTime");

                    b.Property<int?>("RecursoIdRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TareaIdTarea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiempo")
                        .IsRequired()
                        .HasColumnName("Tiempo")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("RecursoIdRecurso");

                    b.HasIndex("TareaIdTarea");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("Parcialplataformas.Recurso", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRecurso");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Nombre");
                });

            modelBuilder.Entity("Parcialplataformas.Tarea", b =>
                {
                    b.Property<string>("IdTarea")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnName("Estado")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estimacion")
                        .HasColumnName("Estimacion")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsableIdRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Titulo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vencimiento")
                        .IsRequired()
                        .HasColumnName("Vencimiento")
                        .HasColumnType("DateTime");

                    b.HasKey("IdTarea");

                    b.HasIndex("ResponsableIdRecurso");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Parcialplataformas.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("Clave")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnName("Usuario")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parcialplataformas.Detalle", b =>
                {
                    b.HasOne("Parcialplataformas.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoIdRecurso");

                    b.HasOne("Parcialplataformas.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaIdTarea");
                });

            modelBuilder.Entity("Parcialplataformas.Recurso", b =>
                {
                    b.HasOne("Parcialplataformas.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("Parcialplataformas.Tarea", b =>
                {
                    b.HasOne("Parcialplataformas.Recurso", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableIdRecurso");
                });
#pragma warning restore 612, 618
        }
    }
}
